#!/bin/bash

#Orignal JP Needry Disables JP Security (Approx.)
JP="1993-11-06-19-01-00"

#Jurassic World Accident Date (Approx.)
JW="2015-24-12-20-30-00"

CD=`date +%Y-%d-%m-%H-%M-%s`
TS=$((`date -jf %Y-%d-%m-%H-%M-%s $CD +%s` - `date -jf %Y-%d-%m-%H-%M-%s $JP +%s`))

echo -e "Jurassic Park, System Security Interface release 2 (Jurassic World)
Version 15.0.0-10.11-ec
Time since last Dinosuar Attack:"
{
 ((d=$TS/(60*60*24)))
 ((h=($TS%(60*60*24))/(60*60)))
 ((m=($TS%(60*60))/60))
 ((s=$TS%60))
 printf "%02dd %02dh %02dm %02ds\n" $d $h $m $s
}